### ISSUE TITLE
fix_pdf.exe: Failed to execute script fix_pdf

### ISSUE THREAD

**Issue by petersobolev** [xdever/OnyxNoteRenderer#2]
Trying to fix annotations in pdf (Note Pro, 2.1.2) using fix_pdf.exe (Windows)
Got:

fix_pdf.exe phantomdox_notes.pdf
Traceback (most recent call last):
  File "fix_pdf.py", line 48, in <module>
  File "site-packages\pdfrw\pdfreader.py", line 619, in __init__
  File "site-packages\pdfrw\pdfreader.py", line 457, in parsexref
  File "site-packages\pdfrw\pdfreader.py", line 369, in parse_xref_stream
  File "site-packages\pdfrw\pdfreader.py", line 139, in readstream
  File "site-packages\pdfrw\tokens.py", line 229, in exception
pdfrw.errors.PdfParseError: Expected endstream endobj (line=13152, col=1, toke
n='startxref')
[16400] Failed to execute script fix_pdf

**Comment by RobertCsordas** [comment]
Could you attach a file where this happens?

Just about the filename: are those notes, or a pdf annotated by the reader app? Because the tool works for the reader app and not the notes exported by the notes app (for the notes app there is the onyx_render tool).

**Comment by petersobolev** [comment]
This is annotated pdf, so I thought it should be fixed with fix_pdf... See attach:
[phantomdox_notes.pdf](https://github.com/xdever/OnyxNoteRenderer/files/3858245/phantomdox_notes.pdf)

**Comment by RobertCsordas** [comment]
The file has wrong format, it doesn't terminate some streams it uses. However, this doesn't seem to bother the PDF viewer programs. The PDF parser library is not mine, so it would take some time to figure out how can I make it ignore such errors (although I have an idea). However, I'm wondering whether the Onyx saved the PDF in the wrong format, or it was already like that. Do you have the raw PDF that is unannotated/ Could you also attach that so I can check what caused the error? For more info, here is the output of qpdf --check:

```bash
$ qpdf --check phantomdox_notes.pdf
WARNING: phantomdox_notes.pdf (xref stream: object 2240 0, offset 1263381): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 2107 0, offset 1155061): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 2040 0, offset 1105689): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1688 0, offset 859934): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1678 0, offset 851066): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1677 0, offset 850370): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1577 0, offset 778423): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1417 0, offset 633253): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1415 0, offset 632367): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1396 0, offset 616150): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1377 0, offset 602577): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1015 0, offset 332821): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1007 0, offset 331194): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 1003 0, offset 328234): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 996 0, offset 324166): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 989 0, offset 319542): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 988 0, offset 318848): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 987 0, offset 318154): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 986 0, offset 317460): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 985 0, offset 316766): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 982 0, offset 315373): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 978 0, offset 309008): expected endobj
WARNING: phantomdox_notes.pdf (xref stream: object 974 0, offset 304705): expected endobj
WARNING: phantomdox_notes.pdf: reported number of objects (2241) is not one plus the highest object number (2239)
checking phantomdox_notes.pdf
PDF Version: 1.5
File is not encrypted
File is not linearized
```

**Comment by petersobolev** [comment]
Here is [original](https://buildmedia.readthedocs.org/media/pdf/phantomdox/latest/phantomdox.pdf).

Thank you for your work anyway!

**Comment by RobertCsordas** [comment]
Well, I can confirm that the onyx wrote the bad blocks into the PDF. I'll try to modify the pdfrw library to ignore those errors, however it seems not to be that easy.

You're welcome :)!

**Comment by rostam2000** [comment]
Thanks for all the hard work, xdever. I can confirm that I have the same issue on a Mac setup, so it seems that the culprit is indeed the PDF as produced by Onyx. Could you kindly update us on this, and whether you have found a fix via pdfrw?

Many thanks again!

**Comment by RobertCsordas** [comment]
Sorry for the long delay. Unfortunately, I was unable to figure out a fix in the time I had for this project. I modified PDFRW to ignore the malformed block endings, but then I run into other issues. Maybe somebody who is more familiar with PDF internals should take a look.

However, I noticed that this happens very rarely, and re-saving on Onyx usually helps. Also, if you are on UNIX, you can fix the corrupted PDF with QPDF easily, and then run the tool on the fixed file:

```
qpdf <corrupted source> <new, fixed target>
```
