### ISSUE TITLE
AttributeError: __enter__ with cairo.PDFSurface

### ISSUE THREAD

**Issue by thstyl2000** [xdever/OnyxNoteRenderer#5]
First of all thank you very much for your efforts!! I am on Ubuntu 20.04 and I get the following error when I try to convert from my Max2Pro:

`Traceback (most recent call last):
  File "/home/kioftes/bin/onyx_render.py", line 167, in render
    render_pdf(note, tmpdir, fname)
  File "/home/kioftes/bin/onyx_render.py", line 63, in render_pdf
    with cairo.PDFSurface(filename, *letter) as context:
AttributeError: __enter__
`
Would be grateful for any hints to a solution...!

**Comment by duburcqa** [comment]
I just encountered the same issue and solved it, so I can give you the answer :) Better late than never! Just update cairo to the latest release available (1.20) by doing `pip3 install pycairo --upgrade`

**Comment by cameronkerrnz** [comment]
Ubuntu 20.04 comes with version 1.16.2 of pycairo as I write this, and that that version of pycairo doesn't support being used as a context manager (that what you can infer from __enter__ not being available, as that's an essential requirement for being used as a context manager).

You can get the older version of the documentation at https://github.com/pygobject/pycairo/blob/v1.16.2/docs/tutorial.rst (select the tag 
The proper way to deal to this on Linux systems is to not use the (older) version of pycairo that was installed via the system's package manager; attempting to use 'pip3 install pycairo --upgrade' (when run as root) may end up getting you into trouble (overwriting files that should be managed by the system package manager).

Instead, create a virtualenv (if you are not using it already), or stick with the older version (which would get maintained and updated by system vendor) and use the documentation that matches that version.
